"""add provider to agent_config

Revision ID: 28809d9e5ee9
Revises: 6a7966f48a58
Create Date: 2026-06-12 15:52:16.366444
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '28809d9e5ee9'
down_revision: Union[str, None] = '6a7966f48a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('provider', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'provider')
    # ### end Alembic commands ###
