"""add embedding_provider to agent_config

Revision ID: ab02657e11d8
Revises: 28809d9e5ee9
Create Date: 2026-06-12 16:06:15.030883
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ab02657e11d8'
down_revision: Union[str, None] = '28809d9e5ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('embedding_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'embedding_provider')
    # ### end Alembic commands ###
